version: "3"

services:
  nonebot:
    build: .
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./:/bbot-ng/"
    restart: always
    container_name: bbot-ng
    ports:
      - "8080:8080"
    env_file:
      - ".env.dev"

  go-cqhttp:
    image: silicer/go-cqhttp:latest
    container_name: go-cqhttp
    restart: always
    depends_on:
      - nonebot
    expose:
      - 5700
      - 6700
    ports:
      - 5700:5700
      - 6700:6700
    volumes:
      - /etc/localtime:/etc/localtime
      - ./go-cq-config:/data

networks:
  default:
    external:
      name: gateway