version: "3"

services:
  nonebot:
    build: .
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./:/bbot-ng/"
    ports:
      - "8080:8080"
    env_file:
      - ".env.dev"
    environment:
      - ENVIRONMENT=dev
      - APP_MODULE=bot:app
      - SECRET # 通过 SECRET=xxx nb up -d 传递密钥
      - ACCESS_TOKEN # 通过 ACCESS_TOKEN=xxx nb up -d 传递密钥
      - MAX_WORKERS=1 # 如果你有多个QQ，且存在 self_id 指定，多个 worker 会导致无法找到其他 websocket 连接

  go-cqhttp:
    image: silicer/go-cqhttp:latest
    container_name: go-cqhttp
    restart: always
    expose:
      - 5700
      - 6700
    ports:
      - 5700:5700
      - 6700:6700
    volumes:
      - /etc/localtime:/etc/localtime
      - ./volumes/go-cqhttp/data:/data

networks:
  default:
    external:
      name: gateway