version: "3"

services:
  nonebot:
    build: .
    restart: always
    container_name: bbot-ng
    ports:
      - "666:9999"
    volumes:
      - ./dbs:./bbot-ng/dbs

  go-cqhttp:
    image: silicer/go-cqhttp:latest
    container_name: go-cqhttp
    restart: always
    depends_on:
      - nonebot
    ports:
      - "777:9999"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./go-cq-config:/data